# Password Generator Project
# This is a simple password generator that allows the user to specify the number of letters, symbols, and numbers they want in their password.
# The program then generates a random password based on the user's specifications.
# The password is generated using a combination of letters, symbols, and numbers, and is shuffled to ensure randomness.
# The final password is printed to the console.

# Importing the random module to generate random choices
import random

# Defining the lists of characters to choose from
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


print("Welcome to the PyPassword Generator!")
# Prompting the user for input
nr_letters = int(input("How many letters would you like in your password?\n"))
nr_symbols = int(input(f"How many symbols would you like?\n"))
nr_numbers = int(input(f"How many numbers would you like?\n"))
# Creating a empty list to hold the password characters
password_list = []
# Generating the password based on user input
# The password is generated by appending random choices from the letters, symbols, and numbers lists to the password_list.
# Generating the letters, symbols, and numbers based on user input
# The for loops iterate over the range of the number of characters specified by the user and append random choices to the password_list.
for char in range(1, nr_letters  + 1):
    password_list.append(random.choice(letters))
for char1 in range(1, nr_symbols  + 1):
    password_list.append(random.choice(symbols))
for char2 in range(1, nr_numbers  + 1):
    password_list.append(random.choice(numbers))
# shuffling the password_list to ensure randomness
random.shuffle(password_list)

# Joining the characters in the password_list to create the final password
password = ""
for char in password_list:
    password += char
# Printing the final password to the console
print(f"Your password is: {password}")